option to listen on UDP.
AerisCloud/ansible-rsyslog pull request #10
Opened 2017-05-25 11:23 UTC by tokyowizard

When rsyslogd gets installed, the default setting is commented out, so UDP reception is off by default.

This PR allows to turn it on.

New variables:

  - `use_rsyslog_udp` (default: `false`), set to `true` so that rsyslogd will listen on UDP.
  - `use_rsyslog_udp_port` (default: `514`), sets the UDP port to listen on.

2017-05-25 12:10 UTC, MiLk requested changes

2017-05-25 12:10 UTC, MiLk commented on tasks/main.yml
> +    dest=/etc/rsyslog.conf
Please use a template a put it in `/etc/rsyslog.d/00_udp_server.conf`

2017-05-26 03:00 UTC, tokyowizard commented on tasks/main.yml
> +    dest=/etc/rsyslog.conf
good idea. thanks! will do.

2017-05-26 03:11 UTC, MiLk approved these changes

2017-05-26 03:11 UTC, merged