add tls support to papertrail
AerisCloud/ansible-rsyslog pull request #9
Opened 2017-05-19 08:59 UTC by tokyowizard

Base on [Papertrail's instructions](http://help.papertrailapp.com/kb/configuration/encrypting-remote-syslog-with-tls-ssl/#rsyslog).

New variable: `use_rsyslog_tls`. Defaults to false.

2017-05-19 09:11 UTC, MiLk requested changes

2017-05-19 09:11 UTC, MiLk commented on tasks/main.yml
> +    name: "rsyslog-gnutls"
There is some weird bugs with the versions in the ubuntu repos (8.16.0).
> unexpected GnuTLS error -50 in nsd_gtls.c:530: The request is invalid. [v8.16.0 try http://www.rsyslog.com/e/2078 ] 

You should install it from the PPA http://www.rsyslog.com/downloads/download-v8-stable/

2017-05-19 09:11 UTC, MiLk commented on tasks/main.yml
> +  when: use_rsyslog_tls|bool == true and rsyslog_conf.stat.exists|bool and logstash_forwarder is defined
there should be an `use_papertrail` flag here.
It's not because you are using TLS that you are using PT.

2017-05-19 09:11 UTC, MiLk commented on tasks/main.yml
> +- name: "Set forwarding (with TLS) in /etc/rsyslog.conf. 1"
Please use a template and put all the following lines together in the same file.

2017-05-19 09:11 UTC, MiLk commented on tasks/main.yml
> +- debug: var=papertrailmd5
Please remove the debug

2017-05-19 09:11 UTC, MiLk commented on tasks/main.yml
> +    name: "rsyslog-gnutls"
```yaml
- name: "Add rsyslog repository"
  apt_repository:
    repo: 'ppa:adiscon/v8-stable'
  tags: ['rsyslog', 'repos']
```

2017-05-19 09:17 UTC, tokyowizard commented on tasks/main.yml
> +    name: "rsyslog-gnutls"
Ok, will do. But next week. I need to get something out today. Thank you for the comments.

2017-05-24 03:22 UTC, MiLk requested changes

2017-05-24 03:22 UTC, MiLk commented on tasks/main.yml
> +  when: rsyslog_conf.stat.exists|bool == true
Why the `== true`?

2017-05-24 03:22 UTC, MiLk commented on tasks/papertrail.yml
> +  when: use_papertrail|bool == true and logstash_forwarder is not defined and papertrailmd5.stdout != 'ba3b40a34ec33ac0869fa5b17a0c80fc'
Please use a variable for the checksum.

2017-05-24 05:48 UTC, MiLk approved these changes

2017-05-24 05:48 UTC, merged